language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e ".[dev]"

script:
  - "flake8 ."
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then travis-sphinx build; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then travis-sphinx deploy; fi